# Generated by Django 6.0.3 on 2026-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="is_alcoholic",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
