# Generated by Django 6.0.3 on 2026-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0002_remove_ingredient_is_alcoholic_cocktail_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailingrediets",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ml", "ml"),
                    ("oz", "oz"),
                    ("tsp", "łyżeczka"),
                    ("tbsp", "łyżka"),
                    ("piece", "sztuka"),
                    ("leaves", "liść"),
                ],
                default="ml",
                max_length=50,
            ),
        ),
    ]
